typography_spectrum: 0.8051726601552218
color:
  brandStrength: 0.5026639013085514
  lightness: 0.008349977899342775
  saturation: 0.6267393326852471
  rhythmicContrast: 0.8403934349771589
  brandColors:
    - '#010006'
    - '#B6C6D6'
    - '#5B6888'
    - '#DC9A78'
    - '#341E2A'
layout_spectrum: 0.22033543838188052
name: amasterofmagic
title: Welcome
description: we've been waiting for you...
navigation:
  - name: >-
      David Lee Brown Actor Magician Martial Artist Stuntman Police Military
      Sanford Meisner Trained Actor
    id: bc35e987-07b9-4767-bd8d-638fdc83a10b
    type: content
